
  web:
    image: alabalistic/flask-garage:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - GOOGLE_APPLICATION_CREDENTIALS=/app/instance/google-speech-to-text-key.json
    volumes:
      - ./instance:/app/instance
      - ./static/profile_pics:/app/app/static/profile_pics
      - ./static/repair_shop_pics:/app/app/static/repair_shop_pics
      - ./logs:/app/logs
    env_file:
      - .env
