version: '3.8'

services:
  web:
    image: alabalistic/flask-garage:latest   
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV= production
      - FLASK_APP=run.py
      - GOOGLE_APPLICATION_CREDENTIALS=/app/instance/google-speech-to-text-key.json
    volumes:
      - ./instance:/app/instance  
      - ./static:/app/app/static
    env_file:
      - .env



