"""Add NewModel.

Revision ID: 67169bf69a5f
Revises: 
Create Date: 2024-07-19 16:32:50.803199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67169bf69a5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_model')
    # ### end Alembic commands ###
