"""Allow user_id to be NULL in posts

Revision ID: 69507b2d3f99
Revises: 99fe993daf01
Create Date: 2024-07-22 11:53:41.258790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69507b2d3f99'
down_revision = '99fe993daf01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
